<?php
include $_SERVER['DOCUMENT_ROOT']."/m/Auth.class.php";
session_start();
class AuthController extends Controller
{
    public $view = 'log_form';
    public $title;

    function __construct()
    {
        parent::__construct();
        $this->title .= 'LOG IN FORM';
    }

//    function setMenu()
//    {
//        parent::setMenu(); // TODO: Change the autogenerated stub
//    }

    //метод, который отправляет в представление информацию в виде переменной content_data
	function index($data){
        $obj = new Auth();
        if($_POST['log']){
            $login = strip_tags($_POST['login']);
            $pass = strip_tags($_POST['pass']);
            $result = $obj->checkUser($login, $pass);
            if($result){
                $_SESSION['login'] = $login;
                return 'You have logged in successfully';
            }
            return "You have entered wrong data";
        }
	}

}

//site/index.php?path=index/test/5