<?php
require_once "../m/Goods.class.php";
class GoodsController extends Controller
{
    public $view = 'goods';
    public $title;

    function __construct()
    {
        parent::__construct();
        $this->title = 'CATALOG';
    }

//    function setMenu()
//    {
//        parent::setMenu(); // TODO: Change the autogenerated stub
//    }

	function showGoods($data){
        $obj = new Goods;
        return $obj->getGoods();
	}


}

//site/index.php?path=index/test/5