<?php

class IndexController extends Controller
{
    public $view = 'index';
    public $title;

    function __construct()
    {
        parent::__construct();
        $this->title .= ' | THE BEST WATCHES!';
    }

//    function setMenu()
//    {
//        parent::setMenu(); // TODO: Change the autogenerated stub
//    }

    //метод, который отправляет в представление информацию в виде переменной content_data
	function index($data){
		 return "Welcome to our online store";
	}

	/*function test($id){

    }
*/

}

//site/index.php?path=index/test/5