<?php
include $_SERVER['DOCUMENT_ROOT']."/PHP_online-store/m/Auth.class.php";
class SignController extends Controller
{
    public $view = 'sign_form';
    public $title;

    function __construct()
    {
        parent::__construct();
        $this->title .= 'SIGN UP FORM';
    }

//    function setMenu()
//    {
//        parent::setMenu(); // TODO: Change the autogenerated stub
//    }

    //метод, который отправляет в представление информацию в виде переменной content_data
	function index($data){
        $obj = new Auth();
        if($_POST['sign']){
            $login = strip_tags($_POST['login']);
            $pass = strip_tags($_POST['pass']);
            $result = $obj->checkLogin($login);
            if(!result){
                $obj->addUser($login, $pass);
                $_SESSION['login'] = $login;
                return 'You have signed in successfully';
            }
            return "This login exists, enter another one";
        }
        return "Please enter required data to sign up our online store";
	}

}

//site/index.php?path=index/test/5